//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SofiaCosmetics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIET_SANPHAM
    {
        public CHITIET_SANPHAM()
        {
            this.CHITIETDONHANGs = new HashSet<CHITIETDONHANG>();
            this.CHITIETGIOHANGs = new HashSet<CHITIETGIOHANG>();
            this.HINHANHs = new HashSet<HINHANH>();
        }
    
        public int MaCTSP { get; set; }
        public int MaSP { get; set; }
        public string TenBienThe { get; set; }
        public decimal Gia { get; set; }
        public Nullable<decimal> GiaKhuyenMai { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public Nullable<int> MaKM { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
        public virtual ICollection<CHITIETDONHANG> CHITIETDONHANGs { get; set; }
        public virtual ICollection<CHITIETGIOHANG> CHITIETGIOHANGs { get; set; }
        public virtual ICollection<HINHANH> HINHANHs { get; set; }
        public virtual KHUYENMAI KHUYENMAI { get; set; }
    }
}
