//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SofiaCosmetics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHMUC
    {
        public DANHMUC()
        {
            this.DANHMUC1 = new HashSet<DANHMUC>();
            this.SANPHAMs = new HashSet<SANPHAM>();
        }
    
        public int MaDM { get; set; }
        public string TenDM { get; set; }
        public Nullable<int> MaCha { get; set; }
        public string MoTa { get; set; }
    
        public virtual ICollection<DANHMUC> DANHMUC1 { get; set; }
        public virtual DANHMUC DANHMUC2 { get; set; }
        public virtual ICollection<SANPHAM> SANPHAMs { get; set; }
    }
}
