//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SofiaCosmetics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIOHANG
    {
        public GIOHANG()
        {
            this.CHITIETGIOHANGs = new HashSet<CHITIETGIOHANG>();
        }
    
        public int MaGH { get; set; }
        public int MaKH { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    
        public virtual ICollection<CHITIETGIOHANG> CHITIETGIOHANGs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
