//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SofiaCosmetics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HINHANH
    {
        public int MaHinh { get; set; }
        public int MaCTSP { get; set; }
        public string DuongDan { get; set; }
    
        public virtual CHITIET_SANPHAM CHITIET_SANPHAM { get; set; }
    }
}
