//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SofiaCosmetics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        public KHACHHANG()
        {
            this.DANHGIAs = new HashSet<DANHGIA>();
            this.DONHANGs = new HashSet<DONHANG>();
            this.GIOHANGs = new HashSet<GIOHANG>();
            this.TINNHANs = new HashSet<TINNHAN>();
        }
    
        public int MaKH { get; set; }
        public string HoTen { get; set; }
        public string Email { get; set; }
        public string MatKhau { get; set; }
        public string SDT { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual ICollection<DANHGIA> DANHGIAs { get; set; }
        public virtual ICollection<DONHANG> DONHANGs { get; set; }
        public virtual ICollection<GIOHANG> GIOHANGs { get; set; }
        public virtual ICollection<TINNHAN> TINNHANs { get; set; }
    }
}
