//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SofiaCosmetics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHUYENMAI
    {
        public KHUYENMAI()
        {
            this.CHITIET_SANPHAM = new HashSet<CHITIET_SANPHAM>();
            this.SANPHAMs = new HashSet<SANPHAM>();
        }
    
        public int MaKM { get; set; }
        public string TenKhuyenMai { get; set; }
        public string MoTa { get; set; }
        public Nullable<double> PhanTramGiam { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public string MaCode { get; set; }
        public Nullable<bool> IsNewUserOnly { get; set; }
    
        public virtual ICollection<CHITIET_SANPHAM> CHITIET_SANPHAM { get; set; }
        public virtual ICollection<SANPHAM> SANPHAMs { get; set; }
    }
}
