//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SofiaCosmetics.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLMyPhamEntities : DbContext
    {
        public QLMyPhamEntities()
            : base("name=QLMyPhamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ADMIN> ADMINs { get; set; }
        public DbSet<CHITIET_SANPHAM> CHITIET_SANPHAM { get; set; }
        public DbSet<CHITIETDONHANG> CHITIETDONHANGs { get; set; }
        public DbSet<CHITIETGIOHANG> CHITIETGIOHANGs { get; set; }
        public DbSet<DANHGIA> DANHGIAs { get; set; }
        public DbSet<DANHMUC> DANHMUCs { get; set; }
        public DbSet<DONHANG> DONHANGs { get; set; }
        public DbSet<GIOHANG> GIOHANGs { get; set; }
        public DbSet<HINHANH> HINHANHs { get; set; }
        public DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public DbSet<KHUYENMAI> KHUYENMAIs { get; set; }
        public DbSet<MENU> MENUs { get; set; }
        public DbSet<SANPHAM> SANPHAMs { get; set; }
        public DbSet<SLIDER> SLIDERs { get; set; }
        public DbSet<TINNHAN> TINNHANs { get; set; }
        public DbSet<TINTUC> TINTUCs { get; set; }
        public DbSet<THANHTOAN> THANHTOANs { get; set; }
        public DbSet<THUONGHIEU> THUONGHIEUx { get; set; }
    }
}
