//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SofiaCosmetics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        public SANPHAM()
        {
            this.CHITIET_SANPHAM = new HashSet<CHITIET_SANPHAM>();
            this.DANHGIAs = new HashSet<DANHGIA>();
        }
    
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public string MoTa { get; set; }
        public int MaDM { get; set; }
        public Nullable<int> MaTH { get; set; }
        public Nullable<int> MaKM { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual ICollection<CHITIET_SANPHAM> CHITIET_SANPHAM { get; set; }
        public virtual ICollection<DANHGIA> DANHGIAs { get; set; }
        public virtual DANHMUC DANHMUC { get; set; }
        public virtual KHUYENMAI KHUYENMAI { get; set; }
        public virtual THUONGHIEU THUONGHIEU { get; set; }
    }
}
